service: tennis-lambda

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
      # - http:
      #     method: any
      #     path: /{any+}
custom:
  serverless-offline:
    noPrependStageInUrl: true
    # useDocker: true
