org: viiinzzz
app: tennis-lambda
service: tennis-lambda

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  # - 'serverless-plugin-typescript'
  # - serverless-plugin-optimize
  - serverless-offline
  - serverless-graph

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3

functions:
  api:
    handler: dist/lambda.handler
    # handler: src/lambda1.handler
    events:
      - http: GET /
      - http: GET /ranks
      - http: GET /details/{any+}
      - http: GET /stats
      - http: ANY /admin
      # - http:
      #     method: any
      #     path: /{any+}
custom:
  # serverless-offline:
  #   noPrependStageInUrl: true
  routeSettings:
    detailedMetricsEnabled: true
    rateLimit: 10
    burstLimit: 3
    # useDocker: true
  # jetpack:
  #   trace: true
  # webpack:
  #   packager: "yarn"
  #   includeModules:
  #     forceExclude:
  #       - aws-sdk
